### PR TITLE
Using requests library for urlencoding

### PR DESCRIPTION
**Pull request by geekypandey**
Pull request
============

Description
-----------

Using requests library for urlencoding.

Motivation and Context
----------------------
To remove additional complexity of this following part and to improve code clarity.
The following loop does exactly what `requests.urllib3.request.urlencode` functions does, using
the library function will help readability and will also help in future refactoring.

Previously :
```python
for i in fields:
    api_signature += str(i) + "="
    if isinstance(fields[i], list):
        for j in fields[i]:
            api_signature += str(j) + ";"
    else:
        api_signature += str(fields[i])
    api_signature += "&"
api_signature = api_signature[:-1]
```

Now:
```python
api_signature += requests.urllib3.request.urlencode(fields)
```

How Has This Been Tested
------------------------

Python version: 3.8
Separate virtualenv with dependencies installed.
Ran tests and passed required ones. ( cannot pass all tests, as the tests are bounded to users api_key and secret )

Screenshots (if appropriate)
----------------------------

Types of changes
----------------

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

Checklist
---------

Go over all the following points, and put an `x` in all the boxes that apply.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

- [] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by VadVergasov — APPROVED** [review]

**Comment by VadVergasov** [comment]
Can you rebase your changes after the lastest commit to master to update GitHub actions workflows to test your changes?

**Comment by geekypandey** [comment]
okay! I have done the rebase.

**Comment by VadVergasov** [comment]
This solution isn't working when a list exists in the fields, because [Codeforces](https://codeforces.com) works not as expected with them when calculating the signature. For lists it encodes list ["VadVergasov", "tourist"] as =['VadVergasov',+'tourist'] but we need to encode as =VadVergasov;tourist;
This should be fixed by [Mike Mirzayanov](https://github.com/MikeMirzayanov).

**Comment by geekypandey** [comment]
you are partially correct. The problem is, if if take example of user info where we can pass list:
```py3
cf = codeforces_api.CodeforcesApi(api_key, api_secret)
user_info = cf.user_info(["VadVergasov", "tourist"])
```
the parameter passed to `_make_request` is `{"handles": "VadVergasov;tourist;"}`
when `urlencode` function encodes it, it converts the unsafe characters `;` to `%3B` as it should, and we are hashing this value.
But in the actually request body we are sending `"handles": "VadVergasov;tourist;"`, so when the server checks hash at its ends it throws error.
We could solve this by using same type of encoding in both hashing and request body.

One solution would be:
```py3
api_signature += requests.urllib3.request.urlencode(fields, safe=";")
```
so it would not convert the `;` to `%3B`

I tried this and it passed the tests.
test_passing

**Comment by VadVergasov** [comment]
So, please, commit this edit and I'll merge it into the master branch.

**Comment by geekypandey** [comment]
done! :-)

**Pull request merged**
